name: 'Akto CI/CD'
description: 'Run akto in ci/cd'
inputs:
  AKTO_DASHBOARD_URL:  
    required: true
  AKTO_API_KEY:  
    required: true
  AKTO_TEST_ID:  
    required: true
  START_TIME_DELAY:
    required: false
runs:
  using: 'node16'
  main: 'index.js'